spring.application.name=personal-finance-tracker

# connexion supabase
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zjirmredusqwtxdibasa
spring.datasource.password=u5WNANIfFltghHIe
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=120000

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
app.jwt.secret=${JWT_SECRET:ChangeMeOnlyForLocalDevelopment123456789}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
